### ISSUE TITLE
how to solve "serial: timeout" while reading saveral values from modbus device

### ISSUE THREAD

**Issue by huangpeilong** [edgexfoundry/device-modbus-go#108]
// handle command requests
        for i, req := range reqs {
                res, err := d.handleReadCommandRequest(deviceClient, req)
                if err != nil {
                        driver.Logger.Info(fmt.Sprintf("Read command failed. Cmd:%v err:%v \n", req.DeviceResourceName, err))
                        return responses, err
                }
                responses[i] = res
                // PLC may be a little slow to handle request, if you modbus device return err like "serial: timeout",
                // you can add time.Sleep(10000000) here to handle this
        }
![log](https://user-images.githubusercontent.com/19727427/70715695-c7204e00-1d25-11ea-975c-9830df1cb6d6.png)

**Comment by weichou1229** [comment]
No problem, we can add the timeout parameter when creating the Modbus connection.
https://github.com/goburrow/modbus
