### ISSUE TITLE
Swap word doesn't work for float32 type

### ISSUE THREAD

**Issue by novuscy** [edgexfoundry/device-modbus-go#151]
There are some occasions where the two words of a float32 type need to be swapped, but right now it seems that the isWordSwap option only works for INT type.

**Comment by nbfhscl** [comment]
maybe the option isWordSwap should be replaced by isLittleEndian.

0x0102 as an example for 16 bits data, 
isByteSwap\isLittleEndian|false|true|
|-|-|-|
false|0102|0201|
true|0201|0102|

0x01020304 as an example for 32bits data
isByteSwap\isLittleEndian|false|true|
|-|-|-|
false|01020304|04030201|
true|02010403|03040102|

0x0102030405060708 as an example for 64bits data
isByteSwap\isLittleEndian|false|true|
|-|-|-|
false|0102030405060708|0807060504030201|
true|0201040306050807|0708050603040102|
