### ISSUE TITLE
Read float16 data from sensor

### ISSUE THREAD

**Issue by flucciarini** [edgexfoundry/device-modbus-go#179]
I have a device that expose measure in float16 data type. Is possible to add this data type to driver?

**Comment by cloudxxx8** [comment]
is there a standard for float16?

**Comment by flucciarini** [comment]
I looking for something in golang and found this
[https://github.com/x448/float16](https://github.com/x448/float16)

**Comment by lindseysimple** [comment]
EdgeX doesn't support float16 since float16 is not a standard type for Go and modbus, closing this as it is out of scope.
