### ISSUE TITLE
Convert to Go Module

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/device-modbus-go#18]
This service needs to be converted to a Go module in order to eliminate the use of glide.

More information
https://github.com/golang/go/wiki/Modules#migrating-to-modules

Note that the device-sdk-go is already a module.

Recommend this be sequenced after a PR is merged to address the following issue
https://github.com/edgexfoundry/device-sdk-go/issues/173

**Comment by cloudxxx8** [comment]
fixed by #20 
@SteveOss please help close this issue.  thanks
