### ISSUE TITLE
why "function : INPUT_REGISTERS"could has access of write?

### ISSUE THREAD

**Issue by hongda3141** [edgexfoundry/device-modbus-go#180]
hello , 
i have a question about the function ```(c *ModbusClient) SetValue``` in file "modbusclient.go (line: 88)" :

```
case INPUT_REGISTERS:
		result, err = c.client.WriteMultipleRegisters(uint16(modbusCommandInfo.StartingAddress), modbusCommandInfo.Length, value)   
  ```
in modbus protocol , the INPUT_REGISTERS do not have the write access, why convert to WriteMultipleRegisters here?

thank you for your answer , very much

**Comment by weichou1229** [comment]
@hongda3141 You're right, DISCRETES_INPUT and INPUT_REGISTERS should remove from the switch case.

**Comment by hongda3141** [comment]
thankyou for your answer !!
