### ISSUE TITLE
[snap] add RTU support (currently only works in devmode)

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-modbus-go#181]
The [documentation for device-modbus](https://docs.edgexfoundry.org/1.2/examples/Ch-ExamplesAddingModbusDevice/#add-device-service-to-docker-compose-file) instructs users to specify the **privileged** flag when deploying the service via `docker-compose`. This flag essentially allows the service to run unconfined.

When using the snap of device-modbus, since the snap is fully confined, AppArmor prevents the service from accessing serial devices in the way as when deployed via docker. In order to work around this limitation, the snap must be installed using the `--devmode` option, which like docker's privileged mode, allows the service to run unconfined.

This issue is about adding support to the snap to allow it to be granted permission to access serial devices without having to specify `--devmode`.

This issue is was created in response to: https://github.com/edgexfoundry/device-modbus-go/issues/178

**Version**: 1.2.1-20200612+fdf900d  (1255)

**Comment by lindseysimple** [comment]
Snap has been removed from EdgeX, closing the issue.
