### ISSUE TITLE
Problem with communication between Modbus and MQTT

### ISSUE THREAD

**Issue by CesarCastillo-90** [edgexfoundry/device-modbus-go#199]
Hello everyone, I hope you are well.
For communication with Edgex Foundry via MODBUS TCP I am using docker-compose Hanoi master version. I have followed the tutorial found on EdgeX https://docs.edgexfoundry.org/1.3/examples/Ch-ExamplesAddingModbusDevice/, however I get to a point where I don't know what to do.
I have managed to add the device profile to the docker, but I have not managed to make the connection to observe the device through MQTT. To do the initial test I am using the ModbusPal 1.6c simulator. If you can guide me through the step by step to achieve the desired objective, it would be very useful. I remain attentive to your comments.

**Comment by lenny-intel** [comment]
Please do not create these issue duplicate to you posts in Slack. Close as already asked in Slack
