### ISSUE TITLE
Modbus not support register 0

### ISSUE THREAD

**Issue by yanghailei2021** [edgexfoundry/device-modbus-go#272]
When the configuration register address is 0, the register value output through tty is 0xFF 0xFF.
I'm using  docker of hanio vesion.

**Comment by cloudxxx8** [comment]
In Hanoi, the register starting address is one-based value, so it starts from 1, not 0.
In the new release, Ireland, it becomes zero-based value, and it should work as your expectation.

**Comment by yanghailei2021** [comment]
Yes, I'm using Ireland, and it work now.
