### ISSUE TITLE
CreateDeviceProtocol for RTU  Error code: 400 , message: device json decoding failed

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/device-modbus-go#289]
<img width="1186" alt="截圖 2021-11-03 上午11 17 17" src="https://user-images.githubusercontent.com/38970513/140005610-64821cc4-08ec-45ca-8857-c31b9715147f.png">

**Comment by weichou1229** [comment]
@bighb69738 Could you help to check the error logs from core-metadata?

**Comment by bighb69738** [comment]
@weichou1229 
When i chose device resource DO, it can pass.
And i used the example profile which name is "Modbus-RTU-IO-Module".

**Comment by bighb69738** [comment]
@weichou1229 
Now I use the device resource DO or DO0, it also can pass.
