### ISSUE TITLE
Set up the Modbus RTU Device but use the TCP protocol ?

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/device-modbus-go#290]
Set up the Modbus RTU Device and create the device entity to the EdgeX. 
https://docs.edgexfoundry.org/2.0/examples/Ch-ExamplesAddingModbusDevice/

There is a little weird about the protocol setting.

---
"labels":[ 
                  "IO Module",
                  "Modbus RTU"
               ],
               "serviceName": "device-modbus",
               "profileName": "Ethernet-Temperature-Sensor",
               "protocols":{
                  "**modbus-tcp**":{
                     "Address" : "/dev/ttyUSB0",
                     "BaudRate" : "19200",
                     "DataBits" : "8",
                     "StopBits" : "1",
                     "Parity" : "N",
                     "UnitID" : "1",
                     "Timeout" : "5",
                     "IdleTimeout" : "5"
                  }
  },

---
My question is about why we set up the Modbus RTU Device but use the TCP protocol ??

**Comment by weichou1229** [comment]
It's a typo, you can find the correct example config at https://github.com/edgexfoundry/device-modbus-go/blob/main/cmd/res/devices/modbus.test.devices.toml#L25

**Comment by bighb69738** [comment]
@weichou1229 
Thank you!
