### ISSUE TITLE
Fail to create read command connection info.

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/device-modbus-go#293]
**docker logs edgex-modbus** 
![截圖 2021-11-11 下午3 11 31](https://user-images.githubusercontent.com/38970513/141254095-2fdf3c14-97ec-4326-90d9-4fab1d1a6f39.png)

**device profile**
<img width="804" alt="截圖 2021-11-11 下午4 03 15" src="https://user-images.githubusercontent.com/38970513/141260769-a9b9cfb2-94cd-49ca-ace4-901c465d1c77.png">

**docker-compose** 
<img width="761" alt="截圖 2021-11-11 下午3 13 29" src="https://user-images.githubusercontent.com/38970513/141254349-d3a2e354-350b-4ab0-b49a-4ce8c6e724ea.png">

**device setting**
![截圖 2021-11-11 下午3 16 44](https://user-images.githubusercontent.com/38970513/141254730-fae26db8-536b-46c5-8cdf-594c91912082.png)

I tried to use the minimalmodbus to get the readings from the sensor by RTU and that can work.
Do I need to add the deviceCommands or Timeout ??

**Comment by weichou1229** [comment]
Yes, you can to define the protocol properties according to the sample https://github.com/edgexfoundry/device-modbus-go/blob/main/cmd/res/devices/modbus.test.devices.toml#L25

**Comment by bighb69738** [comment]
@weichou1229  
Thank you. I hope you have a good day.
