### ISSUE TITLE
Error occurs when reading resource Readings

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/device-modbus-go#295]
<img width="1438" alt="截圖 2021-11-15 下午3 54 30" src="https://user-images.githubusercontent.com/38970513/141743268-5f1683e0-8d35-468a-9961-32056f0cafd3.png">

**Comment by weichou1229** [comment]
@bighb69738 Please provide the steps and configuration to recreate this issue.

**Comment by lenny-intel** [comment]
@bighb69738 , can we close this old issue?
