### ISSUE TITLE
Update due to Device changes and Schedule* deprecation

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-modbus-go#30]
The example configuration file needs to be updated to the replacement of `Device.Addressable` with `Device.Protocols`, and the deprecation of Schedule* objects by device-sdk-go.

The same `Device` **configuration.toml** and example driver changes that were made to device-sdk-go in commit [fc71221](https://github.com/edgexfoundry/device-sdk-go/commit/fc712212962e7a52da8ff0b7d6a8734cc5af8bdd) need to be applied. 

Likewise the Schedule* **configuration.toml** changes (see device-sdk-go commit [2db9552](https://github.com/edgexfoundry/device-sdk-go/commit/2db9552350484545cc2f0750a9a33b6f572fc05c) also need to be applied.

**Comment by cloudxxx8** [comment]
@weichou1229 is working on this issue and will open PR after https://github.com/edgexfoundry/device-sdk-go/issues/197 closed
