### ISSUE TITLE
Modbus-TCP-Device not found

### ISSUE THREAD

**Issue by ngocnguyenbk12** [edgexfoundry/device-modbus-go#304]
Hi, I just start with edgex foundry
i done with random number device
now i move to Modbus.
i do follow the instruction, i see my Modbus Device when I GET: localhost:48082/api/v1/device:
 {
        "id": "169e8e92-25f1-429d-b587-6b30d8b3f4f4",
        "name": "Modbus-TCP-Device",
        "adminState": "UNLOCKED",
        "operatingState": "ENABLED",
        "labels": [
            "Air conditioner",
            "modbus TCP"
        ],
        "commands": [
            {
                "created": 1642232444536,
                "modified": 1642232444536,
                "id": "f76a8303-d035-46d5-9672-99f83dffacba",
                "name": "Configuration",
                "get": {
                    "path": "/api/v1/device/{deviceId}/Configuration",
                    "responses": [
                        {
                            "code": "200",
                            "description": "Get the Configuration",
                            "expectedValues": [
                                "DemandWindowSize",
                                "LineFrequency"
                            ]
                        },
                        {
                            "code": "500",
                            "description": "internal server error"
                        }
                    ],
                    "url": "http://edgex-core-command:48082/api/v1/device/169e8e92-25f1-429d-b587-6b30d8b3f4f4/command/f76a8303-d035-46d5-9672-99f83dffacba"
                },

but when i try to get value from GET: http://localhost:48082/api/v1/device/169e8e92-25f1-429d-b587-6b30d8b3f4f4/command/f76a8303-d035-46d5-9672-99f83dffacba

And it show me this:

Configuration for Device: Modbus-TCP-Device not found; GET /api/v1/device/169e8e92-25f1-429d-b587-6b30d8b3f4f4/Configuration

Can U guys help me,
Thank you so much.

**Comment by cloudxxx8** [comment]
If you are a new starter, could you please try to use the latest version?  It is v2.1 now, and it is the long term support version.

**Comment by ngocnguyenbk12** [comment]
aw, lemme try at newer version

**Comment by lenny-intel** [comment]
@ngocnguyenbk12 , can we close this issue?

**Comment by iain-anderson** [comment]
closing as inactive
