### ISSUE TITLE
DeviceClient calculates command length using raw type

### ISSUE THREAD

**Issue by natedg7** [edgexfoundry/device-modbus-go#370]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
This issue is located in the Modbus Device Service

### Is this a regression?
Not sure.

### Description and Minimal Reproduction [**REQUIRED**]
Configure a modbus device to query holding registers with rawType of uint16 and value type of Float32. The number of registers the device should be requesting of the modbus server is 2 (16 * 2 = 32 floating point bits), but it only requests 1.

## 🔥 Exception or Error
n/a

## 🌍  Your Environment
Main branch
MacOS (arm64)

It seems that deviceclient.go on line 75 (as of the posting of this) passes in the rawType to calculateAddressLength. Holding registers are 16 bits wide, and the rawType passed in, uint16, is also 16 bits. It seems that replacing rawType with req.Type fixes this issue.

I'm reporting this as an issue instead of just as a PR, as I'm not sure if there was a reason for this, or maybe just some way that I've misconfigured my system. Changing rawType to req.Type did fix this issue on my end though.

**Comment by cloudxxx8** [comment]
this works as design.  due to the transform of device service, rawType might be different from the valueType.
Please see the use case in the document.
https://docs.edgexfoundry.org/2.2/examples/Ch-ExamplesModbusdatatypeconversion/
