### ISSUE TITLE
How To Add more metadata to the Events ? Maybe TAGS

### ISSUE THREAD

**Issue by FabioBoarettiDosSantos** [edgexfoundry/device-modbus-go#406]
Please,

Can I have some guidance howe to include more METADATA to the event. 
I`m working with the IRELAND version at moment. MODBUS GOLANG

{"apiVersion":"v2","requestId":"20c74da2-849d-4955-a1d4-7eaffdf74152","event":{"apiVersion":"v2","id":"299f4034-815e-4a29-b611-e4fd6181b6f4","deviceName":"DGS-SOUST","profileName":"DGS-EXT","sourceName":"ReadyStatusBit","origin":1675107969704251870,"readings":[{"id":"bc3b339b-29b2-45d2-9109-2c95ff7cd79a","origin":1675107969704251870,"deviceName":"DGS-SOUST","resourceName":"ReadyStatusBit","profileName":"DGS-EXT","valueType":"String","value":"READY"}]}}

Thank You So Much [ ]

**Comment by cloudxxx8** [comment]
duplicated to https://github.com/orgs/edgexfoundry/discussions/43
