### ISSUE TITLE
Accept DISCRETES_INPUT and DISCRETE_INPUTS as primary table name

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/device-modbus-go#512]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for device-modbus

### Description [**REQUIRED**]
Since the `DISCRETES_INPUT` looks like a fairly obvious typo, the best way is to accept both `DISCRETE_INPUTS` and `DISCRETES_INPUT`. It's not an ideal situation as the typo is in the spec itself, but using the name from the spec could cause further confusion. 
![image](https://github.com/edgexfoundry/device-modbus-go/assets/11187505/0e83bb6b-1b1e-4df7-a8b2-351e3c2f67ac)
https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf

### Describe the solution you'd like
The device-modbus should accept both `DISCRETES_INPUT` and `DISCRETE_INPUTS`.

**Comment by lenny-intel** [comment]
@jumpingliu Is this enhancement going in for Napa?
