### ISSUE TITLE
How to write yaml for device-modbus 

### ISSUE THREAD

**Issue by Liguangwei0321** [edgexfoundry/device-modbus-go#532]
在编译SDK verison 3.1 napa时，yaml报错，提示不完整；
1.请问如何书写yaml，填写哪些必要元素
2.为什么2.0版本有完整的res/toml文件，3.1版本的yaml有很多空缺，没有完整示例
填写configration.yaml后出现错误：
pi@pi:~/edgex/modbusdev/device-modbus-go/cmd$ ./device-modbus
level=INFO ts=2023-12-13T07:07:51.171137603Z app=device-modbus source=config.go:731 msg="Loading configuration file from res/configuration.yaml"
level=INFO ts=2023-12-13T07:07:51.172127639Z app=device-modbus source=config.go:251 msg="Private configuration loaded from file with 0 overrides applied"
level=INFO ts=2023-12-13T07:07:51.173194565Z app=device-modbus source=httpserver.go:149 msg="Web server starting (localhost:59901)"
**level=ERROR ts=2023-12-13T07:07:51.173281435Z app=device-modbus source=messaging.go:45 msg="MessageBus configuration is incomplete, missing common config? Use -cp or -cc flags for common config."
level=ERROR ts=2023-12-13T07:07:51.173335954Z app=device-modbus source=bootstrap.go:27 msg="Device Service bootstrapping failed"**

配置文件如下：
MaxEventSize: 0 
Writable:
  LogLevel: DEBUG

Service:
  Host: localhost
  Port: 59901
  StartupMsg: device modbus started
  MaxRequestSize: 0 
  RequestTimeout: "5s"

MessageBus:
  Host: "localhost"
  Port: 6379
  Type: "redis"
  AuthMode: "usernamepassword"  
  SecretName: "redisdb"  
  Optional:
    ClientId: "device-modbus"
    Qos: "0"
    KeepAlive: "10" 
    Retained: "false"
    AutoReconnect: "true"
    ConnectTimeout: "5" 
    SkipCertVerify: "false" 

Device:
  ProfilesDir: ""
  DevicesDir: ""

Registry:
  Host: "localhost"
  Port: 8500
  Type: "consul"

Clients:
  Clients.core-data:
    Protocol: "http"
    Host: "localhost"
    Port: 59880

设备：树莓派
系统：ubuntu

**Comment by jiekechoo** [comment]
`level=ERROR ts=2023-12-13T07:07:51.173281435Z app=device-modbus source=messaging.go:45 msg="MessageBus configuration is incomplete, missing common config? Use -cp or -cc flags for common config."`

Here is a guide: https://docs.edgexfoundry.org/3.1/microservices/configuration/CommonCommandLineOptions/ you could refer.

Try this command: 
```
./device-modbus -cp -d -o
```

**Comment by Liguangwei0321** [comment]
> `level=ERROR ts=2023-12-13T07:07:51.173281435Z app=device-modbus source=messaging.go:45 msg="MessageBus configuration is incomplete, missing common config? Use -cp or -cc flags for common config."`
> 
> 这里有一个指南：https://docs.edgexfoundry.org/3.1/microservices/configuration/CommonCommandLineOptions/您可以参考。
> 
> 尝试这个命令：
> 
> ```
> ./device-modbus -cp -d -o
> ```

使用你提示的命令，依然有错误：
level=ERROR ts=2023-12-18T01:47:29.451021229Z app=device-modbus source=messaging.go:45 msg="MessageBus configuration is incomplete, missing common config? Use -cp o
![Uploading mberror.png…]()
