### ISSUE TITLE
Add rawType attribute to define device reading binary data type

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/device-modbus-go#78]
Some device will store data as int16 instead of float32, for example:
1. device read the **temperature 26.3** °C
2. device multiply 26.3 by 100, then convert the result **2630** to binary and store into the register.
![image](https://user-images.githubusercontent.com/11187505/63496468-8e4d3680-c4f4-11e9-8454-7fbf1abf6c39.png)

On the device service side, we should treat the binary as int16 data type and we need to divide 2630 by 100, then the final result should be 26.3 and return to core-data, **but the actual result is 26** because we define the int16 as the properties value type.

Solution:
1. Add rawType attribute( INT16, INT32, ...etc)
2. If rawType exist, device-modbus parse the binary data as rawType and then cast the value according to properties value type.

In this case, rawType is INT16, value type is float32, then device-modbus will parse the binary reading data as INT16 and then cast to float32.

**Comment by cloudxxx8** [comment]
related issue: https://github.com/edgexfoundry/device-sdk-go/issues/339
